### ISSUE TITLE
DOC: improvements checklist

### ISSUE THREAD

**Issue by jakevdp** [altair-viz/altair#1060]
There have been a number of questions from users that point to weaknesses in our docs.  This issue is an attempt to compile them into a checklist.

- [x] sort order for legends, columns, etc. (#1059, addressed in #1069)
- [x] Controlling ``rangeStep`` for ordinal charts (#1050, fixed in #1076)
- [ ] Confusing type syntax in API docs (#1051)
- [x] Selections: use of ``encodings`` and ``fields`` (#1049, fixed in #1080)
- [x] Advanced section with more detailed discussion of connection between Altair API, Altair object structure, and Vega-Lite schema structure. (Done in #1062)
- [x] Examples of local vs UTC time & warnings about formatting for dates-as-strings (#1027, addressed in #1087)
- [x] More examples of bindings, sliders, etc. (done in #1113)
- [x] hiding grids, axes, borders (#1009)
- [x] fix discussion of data specification in compound charts (#1079)
- [x] add discussion of data in indices and ``reset_index()`` (#1079)
- [x] Add information about ``data_transformers.consolidate_datasets`` (done in #1081)
- [x] fix sphinx errors (many undefined/duplicate names, etc.) (Done in #1063)
- [x] clean up API docs (done in #1063)

**Comment by adiep2501** [comment]
I am a bit confused on how to add documentation. Is there some sort of workflow guide for the documentation? Also standards and tips?

**Comment by jakevdp** [comment]
@adiep2501 thanks for your interest – no, there's no guide at the moment (I should add that to the checklist!)

The basics are this:

- the source of the documentation is in the [doc](https://github.com/altair-viz/altair/tree/master/doc) subdirectory
- You can edit the RST source (for example, [encoding.rst](https://github.com/altair-viz/altair/blob/master/doc/user_guide/encoding.rst)) which will be processed using [sphinx](http://www.sphinx-doc.org/en/master/) to convert it to HTML (for example, [encoding.html](https://altair-viz.github.io/user_guide/encoding.html)).

If you make any significant changes, it helps to render the docs locally, which you can do by running ``make html`` within the ``doc`` directory (this requires you install all the packages in ``doc/requirements.txt``)

I hope that's clear!

**Comment by adiep2501** [comment]
So I tried to follow your instructions and it turns out it's a bit more complicated.

Here's the instructions for a MacOS. It actually doesn't work but it's most of the way there.
```
$ git clone https://github.com/altair-viz/altair
$ brew cask install chromedriver
$ cd atlair
$ python3 -m venv venv
$ source venv/bin/activate
$ pip install -r requirements.txt -r requirements_doc.txt -r doc/requirements.txt
$ cd doc
$ make html
```

I get a selenium error `selenium.common.exceptions.JavascriptException: Message: javascript error: vl is not defined`. Googling doesn't get me anything useful.

**Comment by jakevdp** [comment]
``vl`` here is the vega-lite library, which is loaded from the web by selenium. Is it possible that your selenium engine is somehow being blocked from accessing the internet?

**Comment by jakevdp** [comment]
(also, FYI the only thing selenium is used for here is generating thumbnails for the example gallery. You may be able to build the rest of the site without it)

**Comment by adiep2501** [comment]
I am working in an corporate environment so it's probably blocked. How do I build without selenium? I am just trying to see the graphs that are produced.

**Comment by jakevdp** [comment]
Hmm... I don't think there's any built-in way to avoid it at the moment, but you could probably comment-out this line to do it: https://github.com/altair-viz/altair/blob/88ec1e01188f4c46d4d686522ca3fc1a881339f3/altair/sphinxext/altairgallery.py#L129

A better solution long-term might be to add logic to catch errors in that line and save a blank place-holder image instead, so that docs could be built without example thumbnails.

**Comment by adiep2501** [comment]
```
  File "/Users/user/altair/venv/lib/python3.7/site-packages/PIL/Image.py", line 2580, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/Users/user/altair/doc/_images/anscombe_plot.png'
```
Still getting an error, looks like something somewhere expects the file to be written.

**Comment by jakevdp** [comment]
Right, you'll have to create a stand-in image somehow.

**Comment by adiep2501** [comment]
Maybe I could just figure out how to make selenium use the proxy?

**Comment by jakevdp** [comment]
Here's a PR that uses a stand-in thumbnail when selenium is not available.

Note, it depends on catching an ImportError so it's best to use this with selenium not installed.

**Comment by jimmywan** [comment]
Any chance that we could add an example for blending map data with a dataframe containing WGS84 coordinates already in it?

This was a snippet from my admittedly extremely naive attempt at just slapping a backing US map on a scatter plot using longitude/latitude as X/Y:
![image](https://user-images.githubusercontent.com/10406673/43669407-58773752-9748-11e8-9cbe-e4e1c4deaa60.png)

```python
counties = alt.topo_feature(data.us_10m.url, 'counties')
background = alt.Chart(counties).mark_geoshape(
    fill='#666666',
    stroke='white'
).encode(
).project(
    type='equirectangular'
)

background + chart
```

**Comment by jakevdp** [comment]
You should be able to use the latitude and longitude encodings, like in this example: https://altair-viz.github.io/gallery/airports.html

**Comment by kindofluke** [comment]
I just opened a PR for adding documentation on Sort to the user guide.

**Comment by kindofluke** [comment]
@jakevdp just started on binding. You can feel free to take a look in the branch [binding-documentation](url
https://github.com/kindofluke/altair/tree/binding-documentation)

this has been my approach: 

- [x ] With adding input elements and bindings the page should just be called `interactions`. 
- [x] Add simple dropdown example
- [x] add an example using filter
- [x] enumerate all of the avail input elements. 
- [x] bind to  "scales" magic for panning and zooming
- [] headers are all out of wack
- [] spelling and proofread

**Comment by jakevdp** [comment]
@kindofluke this looks great! Feel free to open a pull request even if it's still a work in progress – it makes it easier to track commits and see diffs.

**Comment by jakevdp** [comment]
Aside from the type syntax, we've checked all the boxes now! As it's not clear how that last one will be solved, I'm going to go ahead and close this issue
