### ISSUE TITLE
Version 3.0 wish list

### ISSUE THREAD

**Issue by jakevdp** [altair-viz/altair#1395]
It's mostly documentation at this point:

- [x] update DOC references to low-level classes (#1397)
- [x] add new transforms to transform docs (#1387, #1439, #1440, #1441, #1442, #1446)
- [x] update fold transform example (#1390)
- [x] add examples of new composite marks (#1389, #1396, #1398)
- [x] add documentation of new composite marks
- [x] add examples of new encoding channels (#1397, #1401)
- [x] add documentation of new encoding channels
- [x] add documentation of default tooltip behavior & how to disable
- [x] add documentation & examples of wrapped facet (#1410)
- [x] add documentation & examples of wrapped concat
- [x] add documentation & examples of wrapped repeat
- [x] add examples of initializing selections (#1413)
- [x] Bug #1370: respect transformers in HTML export
- [ ] Bug #1411: fix docs for ``alt.expr`` functions (implicit: also update wrapped functions for VL3 additions)
- [ ] #1375 Improve error messages for common gotchas (need to check whether these all still apply in Vega-Lite 3)
