### ISSUE TITLE
v4.0 TODO list

### ISSUE THREAD

**Issue by jakevdp** [altair-viz/altair#1849]
- [x] Update docs for HTML renderer default (Done in #1858)
- [x] Update changelog for Altair changes plus Vega-Lite breaking changes: https://github.com/vega/vega-lite/releases (In progress...)
- [x] move changelog to HTML documentation (#1853)
- [x] Add example/docs for interactive legend (Done in #1850)
- [x] update FAQ for VSCode #1841 (Done in #1858)
- [x] fix schema generation issue (#1847)
- [x] Update troubleshooting for browser compatibility #1802 (Done in #1858)

**Comment by jakevdp** [comment]
https://github.com/altair-viz/altair/releases/tag/v4.0.0
