### ISSUE TITLE
Type hints: Summary issue

### ISSUE THREAD

**Issue by binste** [altair-viz/altair#2951]
Currently, Altair only has a few type hints to help IDEs provide better autocompletion suggestions. More type hints would further help IDEs provide a better development experience as well as static type checkers to catch potential errors before they appear at runtime. Especially applications (e.g. a company-internal web application) and frameworks (e.g. Streamlit, Great Expectations) which want to tightly integrate with Altair could greatly profit from this.

I'd suggest the following approach for Altair which is in line with [Using mypy with an existing codebase](https://mypy.readthedocs.io/en/stable/existing_code.html). Very open for inputs!

## Should happen before the v5 release
- [x] https://github.com/altair-viz/altair/pull/2949 Improvements in here could wait until after v5 but it also fixes some wrong type hints

## v5 or minor release
I think it's preferable to have the following items more or less bundled into one release from which on Altair is declared as a library supporting type checks. This could be a minor release (5.1?) as it should not affect any runtime behaviour. Goal is to have as much as possible of the "public API" of Altair typed and then incrementally do the rest later on if we see value in it.

- [x] https://github.com/altair-viz/altair/pull/2950 after #2949 is merged. This is a prerequisite for the following tasks so that mypy can tell us if the type hints are reasonable. We're in a fortunate position that we have many example charts in the `tests` folder which mypy can use for this.
- [ ] With mypy added in the previous step, we should aim to type as much as possible of the "public API" of Altair so users can get the most benefit out of this exercise. "internal" code can follow later. How about the following prioritization:
  - [x] `schemapi.py`: #3142
  - [x] `altair/vegalite/v5/api.py`: #3143
  - [x] Parts of folders "vegalite", "v5", and "utils": #2976
  - [ ] For the autogenerated files, we should infer types from the VL schema, see https://github.com/altair-viz/altair/issues/2854: #3208
  - [x] Remaining files in utils: mimebundle.py, save.py: #3248 
  - [ ] Finishing touches #3263 
    - [x]  Type hint `Undefined` as `UndefinedType`. Search for `# Remove "ignore" statement once Undefined is no longer typed as Any` in code which was introduced in #2950 to make mypy pass.
    - [x] Go through current code and search for `# type: ignore` and see if any of those mentions can now be removed or better type hinted
    - [x] Some types might still be marked as private as they start with an `_`. Search for `_[A-Z]` to find them and convert to public types if they are used in public parts of the codebase. This way, others can use the types themselves for code that depends on Altair. This was discussed [in this issue](https://github.com/altair-viz/altair/pull/3081#issuecomment-1587319604).
      - [x] Do we need better naming conventions for these types? Are the names clearly representing the intention/meaning of the types?
    - [x] Declare Altair a library which supports type hints (probably by adding `py.typed`) as mentioned in [the mypy docs](https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages) (also note the mention of `zip_safe` and including the file in wheels and sdist, test this) → This allows mypy to use it when imported in other projects. Once https://github.com/microsoft/pylance-release/issues/4059 is fixed we can also finish https://github.com/altair-viz/altair/pull/2927

## After release of the above
- [ ] Remove exclusion of Altair in mypy.ini files in altair_viewer and altair_saver
 
@mattijn @joelostblom Would you be open to this? Input on the release cycle? I could review PRs related to this topic and create some myself.

**Comment by mattijn** [comment]
Yes, I like to be a reviewer in this process!

**Comment by joelostblom** [comment]
I am in favor of making Altair a typed library. I would like to say that I can be help review and create PRs, but to be honest I haven't worked much with explicit types and it is unlikely that I will have time to learn about it in a reasonable timeframe, so I will likely not be of that much help here unfortunately.
