### ISSUE TITLE
MAINT: TODO before 2.0 release

### ISSUE THREAD

**Issue by jakevdp** [altair-viz/altair#459]
- [x] top-level methods

  - [x] ``mark_*``
  - [x] ``hconcat``, ``vconcat``, ``layer``, and associated operator overloading
  - [x] ``configure_*``
  - [x] ``add_selection``
  - [x] ``resolve``
  - [x] ``add_layer``, ``add_honcat``, ``add_vconcat``
  - [x] ``add_transform`` (plus ``add_transform_filter``, etc.?)
  - [x] ``savechart`` method, with outputs to ``html``, ``json``, ``png``, ``eps``
  - [x] ``from_dict``, delegating to ``alt.Root.from_dict`` if necessary

- [x] remove default width/height from charts? (#482) use ``config.view.width/height`` instead

- [x] finalize selection API (#463)

- [x] Should we continue with the ``expr`` stuff? I'm ambivalent... it might be better to make users think about transforms directly, particularly in the context of compound charts. **Decision: keep limited ``expr`` interface**

- [x] top-level wrapper for RepeatSpec? **done in #533**

- [x] Raise useful error when repeating, layering, hconcating, vconcating charts that are invalid.

- [x] Make certain error messages are useful (#480)

- [x] Make certain that object introspection is as useful as possible (e.g. AnyOf definitions)

- [x] sphinx documentation  **see #552**)

  - [x] update altair-plot directive to work with version 2.0
  - [x] new tutorials for layers & selections
  - [ ] incorporate altair-plot into [ipython directive](https://github.com/ipython/ipython/blob/master/IPython/sphinxext/ipython_directive.py)? best approach would involve factoring-out mpl stuff and making display pluggable.
  - [x] clear info on display troubleshooting (now at https://altair-viz.github.io/user_guide/troubleshooting.html)

- [x] Examples

  - [x] update example notebooks
  - [x] Make sure that formatting is consistent
  - [x] Make sure that methods are being used instead of attributes
  - [x] Load all non-local datasets by URL **done in #537**

- [x] Restore settings in ``.travis.yml`` (see #458)

  - [ ] test install with conda
  - [x] test with py2.7
  - [x] restore ``--doctest-modules`` flag
  - [ ] restore documentation build test (complicated by dependency on chromedriver)
